server:
  port: 8081
spring:

  datasource:
    url: jdbc:mysql://localhost:3306/bookshops1
    password: kmd
    username: kmd
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
    ddl-auto: update
